/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Dashboard Overview */
        get: operations["api_dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Dashboard Trends
         * @description 30-day spend-by-type + leakage trend for the Super Admin (audit P-3).
         */
        get: operations["api_dashboard_trends_api_v1_dashboard_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Auth Login
         * @description Authenticate and return a Bearer token + user as JSON.
         */
        post: operations["api_auth_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Auth Me
         * @description Return the current session user + expiry (audit E-10), or 401.
         */
        get: operations["api_auth_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Auth Refresh
         * @description Sliding renewal (audit E-10): extend the caller's session TTL.
         *
         *     Called by the SPA when the session enters its warning window. Rotates the
         *     auth cookie too when cookie issuance is enabled.
         */
        post: operations["api_auth_refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Auth Logout */
        post: operations["api_auth_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Change Password
         * @description Verify the current password and set a new one for the logged-in user.
         */
        post: operations["api_change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Trips */
        get: operations["api_trips_api_v1_trips_get"];
        put?: never;
        /** Api Create Trip */
        post: operations["api_create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Trip Detail */
        get: operations["api_trip_detail_api_v1_trips__trip_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_code}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Settle Trip */
        post: operations["api_settle_trip_api_v1_trips__trip_code__settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Settled Trips */
        get: operations["api_settled_trips_api_v1_settlements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlements/{trip_code}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Settlement Pdf
         * @description Stream the settlement PDF (application/pdf) for a settled/completed trip.
         */
        get: operations["api_settlement_pdf_api_v1_settlements__trip_code__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/driver/salary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Driver Salary
         * @description Read-only salary/batta summary for the logged-in driver.
         */
        get: operations["api_driver_salary_api_v1_driver_salary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Whatsapp Escalations
         * @description Flagged / pending expenses as a chat-thread feed for manager quick-reply.
         */
        get: operations["api_whatsapp_escalations_api_v1_whatsapp_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Create Expense */
        post: operations["api_create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Action Expense */
        post: operations["api_action_expense_api_v1_expenses__expense_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Vehicles */
        get: operations["api_vehicles_api_v1_vehicles_get"];
        put?: never;
        /** Api Create Vehicle */
        post: operations["api_create_vehicle_api_v1_vehicles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Update Vehicle */
        put: operations["api_update_vehicle_api_v1_vehicles__vid__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Toggle Vehicle */
        post: operations["api_toggle_vehicle_api_v1_vehicles__vid__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Get Fleets */
        get: operations["api_get_fleets_api_v1_fleets_get"];
        put?: never;
        /** Api Create Fleet */
        post: operations["api_create_fleet_api_v1_fleets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Get Plans */
        get: operations["api_get_plans_api_v1_fleets_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Update Fleet */
        put: operations["api_update_fleet_api_v1_fleets__fid__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/{fid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Toggle Fleet */
        post: operations["api_toggle_fleet_api_v1_fleets__fid__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Users */
        get: operations["api_users_api_v1_users_get"];
        put?: never;
        /** Api Create User */
        post: operations["api_create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Update User */
        put: operations["api_update_user_api_v1_users__uid__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{uid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Toggle User */
        post: operations["api_toggle_user_api_v1_users__uid__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Drivers */
        get: operations["api_drivers_api_v1_drivers_get"];
        put?: never;
        /**
         * Api Create Driver
         * @description Create a driver user (Trip Manager / Super Admin), with batta profile.
         */
        post: operations["api_create_driver_api_v1_drivers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Api Update Driver
         * @description Update a driver's profile / batta (Trip Manager / Super Admin).
         */
        put: operations["api_update_driver_api_v1_drivers__uid__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{uid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Toggle Driver
         * @description Activate / deactivate a driver (Trip Manager / Super Admin).
         */
        post: operations["api_toggle_driver_api_v1_drivers__uid__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Benchmarks
         * @description Rules & Rates payload: every state benchmark tagged with the caller's
         *     `is_favorite` flag, plus their usual operating state (`home_state_code`).
         */
        get: operations["api_get_benchmarks_api_v1_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/{state_code}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Add Benchmark Favorite
         * @description Add a state to the caller's favorites (any authenticated role).
         */
        post: operations["api_add_benchmark_favorite_api_v1_benchmarks__state_code__favorite_post"];
        /**
         * Api Remove Benchmark Favorite
         * @description Remove a state from the caller's favorites.
         */
        delete: operations["api_remove_benchmark_favorite_api_v1_benchmarks__state_code__favorite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/home-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Api Set Home State
         * @description Store/clear the caller's usual operating state (`users.home_state_code`).
         *
         *     Body ``{"state_code": "UP"}``; an empty/missing value clears it. The code is
         *     validated against the canonical INDIAN_STATES list server-side.
         */
        put: operations["api_set_home_state_api_v1_benchmarks_home_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/sync-live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Sync Benchmarks
         * @description Fetch live state-level diesel prices and upsert them into fuel_benchmarks.
         *
         *     Super Admin / Trip Manager only. Best-effort: tries the goodreturns live
         *     page first and falls back to a maintained static snapshot when the page is
         *     unreachable or unparsable. Returns how many rows were updated plus the
         *     fetched source.
         */
        post: operations["api_sync_benchmarks_api_v1_benchmarks_sync_live_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Billing Overview */
        get: operations["api_billing_overview_api_v1_billing_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Billing Subscribe
         * @description Subscribe to a plan; returns a JSON `redirect_url` to Razorpay.
         */
        post: operations["api_billing_subscribe_api_v1_billing_subscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/vehicle-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Billing Vehicle Slot
         * @description Purchase an extra vehicle slot; returns JSON `redirect_url`.
         */
        post: operations["api_billing_vehicle_slot_api_v1_billing_vehicle_slot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/renew/{plan_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Billing Renew
         * @description Renew an existing subscription (creates Razorpay payment link).
         */
        post: operations["api_billing_renew_api_v1_billing_renew__plan_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Fleets Subscriptions
         * @description Super Admin consolidated view: all fleets with plan & subscription info.
         */
        get: operations["api_fleets_subscriptions_api_v1_fleets_subscriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Onboard Fleet
         * @description Create a transport firm + owner manager + trial in one transaction.
         */
        post: operations["api_onboard_fleet_api_v1_fleets_onboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trip-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api List Trip Templates
         * @description Fleet-scoped reusable routes (feature F-6).
         */
        get: operations["api_list_trip_templates_api_v1_trip_templates_get"];
        put?: never;
        /** Api Create Trip Template */
        post: operations["api_create_trip_template_api_v1_trip_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trip-templates/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Api Delete Trip Template */
        delete: operations["api_delete_trip_template_api_v1_trip_templates__tid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Notifications
         * @description Computed alert feed for the signed-in user (audit F-3).
         *
         *     Super admins see the fleet-wide picture; trip managers only their own
         *     slice. Nothing is persisted — items are derived from the ledger on read.
         */
        get: operations["api_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Analytics Overview
         * @description Cost-per-vehicle, driver-wise leakage, 6-month spend (audit F-4).
         */
        get: operations["api_analytics_overview_api_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whatsapp Webhook Verify
         * @description Meta platform setup: reply with ``hub.challenge`` when the token matches.
         */
        get: operations["whatsapp_webhook_verify_api_v1_whatsapp_webhook_get"];
        put?: never;
        /**
         * Whatsapp Webhook
         * @description Single inbound entrypoint for ALL bot messages (driver + manager).
         *
         *     Resolves the sender's number to a user (by normalized ``+91`` phone), maps
         *     their role to a routing dialect, and either fires the driver/manager flow or
         *     acknowledges-and-drops unknown/unsupported senders. Always returns a quick 200
         *     so Meta does not retry undeliverable events.
         */
        post: operations["whatsapp_webhook_api_v1_whatsapp_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/whatsapp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whatsapp Send
         * @description Send an outbound template message (idempotent, best-effort).
         *
         *     Auth-gated (audit B-3): only an authenticated trip_manager/super_admin may
         *     trigger outbound sends, so Phase-C credentials can never be used as an
         *     open relay. Without a configured ``WHATSAPP_ACCESS_TOKEN`` this remains a
         *     documented no-op so callers can fire-and-forget.
         */
        post: operations["whatsapp_send_api_v1_whatsapp_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api List States
         * @description Return the canonical state list as [{code, name, is_favorite}].
         *
         *     `is_favorite` mirrors the caller's Rules & Rates favorites so client
         *     dropdowns (driver fueling-state picker etc.) can pin starred states to the
         *     top without a second round-trip.
         */
        get: operations["api_list_states_api_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Billing Webhook
         * @description Razorpay server-to-server webhook — signature verified, no auth.
         */
        post: operations["billing_webhook_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness + DB reachability probe for Render/Docker health checks.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthMe
         * @description `GET /auth/me` — no `data` wrapper (client reads `user` directly).
         */
        AuthMe: {
            user: components["schemas"]["AuthUser"];
            /** Expires At */
            expires_at?: number | null;
        };
        /** AuthUser */
        AuthUser: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /**
         * BenchmarkFavoriteAck
         * @description `POST/DELETE /benchmarks/{state_code}/favorite` acknowledgement.
         */
        BenchmarkFavoriteAck: {
            /** State Code */
            state_code: string;
            /** Is Favorite */
            is_favorite: boolean;
        };
        /** BillingOverview */
        BillingOverview: {
            fleet: components["schemas"]["FleetBilling"];
            /** Plans */
            plans: components["schemas"]["Plan"][];
        };
        /** BillingSubscribeResult */
        BillingSubscribeResult: {
            /** Redirect Url */
            redirect_url?: string | null;
            /**
             * Activated
             * @default true
             */
            activated: boolean;
            /**
             * Trial
             * @default false
             */
            trial: boolean;
            /** Payment Link */
            payment_link?: Record<string, never> | null;
        };
        /** BillingVehicleSlotResult */
        BillingVehicleSlotResult: {
            /** Redirect Url */
            redirect_url?: string | null;
            /** Payment Link */
            payment_link?: Record<string, never> | null;
        };
        /** ChangePasswordResult */
        ChangePasswordResult: {
            /** Id */
            id: number;
            /** Password Changed */
            password_changed: boolean;
        };
        /** CreateTripResult */
        CreateTripResult: {
            /** Trip Code */
            trip_code: string;
            /** Status */
            status: string;
        };
        /**
         * DashboardOverview
         * @description Role-aware overview payload (extra keys vary by role).
         */
        DashboardOverview: {
            /** Role */
            role: string;
        } & {
            [key: string]: unknown;
        };
        /** Data[BenchmarkFavoriteAck] */
        Data_BenchmarkFavoriteAck_: {
            data: components["schemas"]["BenchmarkFavoriteAck"];
        };
        /** Data[BillingOverview] */
        Data_BillingOverview_: {
            data: components["schemas"]["BillingOverview"];
        };
        /** Data[BillingSubscribeResult] */
        Data_BillingSubscribeResult_: {
            data: components["schemas"]["BillingSubscribeResult"];
        };
        /** Data[BillingVehicleSlotResult] */
        Data_BillingVehicleSlotResult_: {
            data: components["schemas"]["BillingVehicleSlotResult"];
        };
        /** Data[ChangePasswordResult] */
        Data_ChangePasswordResult_: {
            data: components["schemas"]["ChangePasswordResult"];
        };
        /** Data[CreateTripResult] */
        Data_CreateTripResult_: {
            data: components["schemas"]["CreateTripResult"];
        };
        /** Data[DashboardOverview] */
        Data_DashboardOverview_: {
            data: components["schemas"]["DashboardOverview"];
        };
        /** Data[DriverSalary] */
        Data_DriverSalary_: {
            data: components["schemas"]["DriverSalary"];
        };
        /** Data[ExpenseAccepted] */
        Data_ExpenseAccepted_: {
            data: components["schemas"]["ExpenseAccepted"];
        };
        /** Data[ExpenseActionResult] */
        Data_ExpenseActionResult_: {
            data: components["schemas"]["ExpenseActionResult"];
        };
        /** Data[HomeStateResult] */
        Data_HomeStateResult_: {
            data: components["schemas"]["HomeStateResult"];
        };
        /** Data[LogoutResult] */
        Data_LogoutResult_: {
            data: components["schemas"]["LogoutResult"];
        };
        /** Data[ResourceAck] */
        Data_ResourceAck_: {
            data: components["schemas"]["ResourceAck"];
        };
        /** Data[SessionRefreshResult] */
        Data_SessionRefreshResult_: {
            data: components["schemas"]["SessionRefreshResult"];
        };
        /** Data[SettleTripResult] */
        Data_SettleTripResult_: {
            data: components["schemas"]["SettleTripResult"];
        };
        /** Data[ToggleAck] */
        Data_ToggleAck_: {
            data: components["schemas"]["ToggleAck"];
        };
        /** Data[TripDetailData] */
        Data_TripDetailData_: {
            data: components["schemas"]["TripDetailData"];
        };
        /** Data[dict] */
        Data_dict_: {
            /** Data */
            data: Record<string, never>;
        };
        /** Data[dict[str, Any]] */
        Data_dict_str__Any__: {
            /** Data */
            data: Record<string, never>;
        };
        /** Data[list[EscalationRow]] */
        Data_list_EscalationRow__: {
            /** Data */
            data: components["schemas"]["EscalationRow"][];
        };
        /** Data[list[TripListItem]] */
        Data_list_TripListItem__: {
            /** Data */
            data: components["schemas"]["TripListItem"][];
        };
        /** Data[list[dict]] */
        Data_list_dict__: {
            /** Data */
            data: Record<string, never>[];
        };
        /** Data[list[dict[str, Any]]] */
        Data_list_dict_str__Any___: {
            /** Data */
            data: Record<string, never>[];
        };
        /** DriverSalary */
        DriverSalary: {
            /** Profile */
            profile?: Record<string, never>;
            /** Trips */
            trips?: components["schemas"]["DriverSalarySummary"][];
            totals: components["schemas"]["DriverSalaryTotals"];
        };
        /**
         * DriverSalarySummary
         * @description Per-trip batta/settlement line on the driver salary view.
         */
        DriverSalarySummary: {
            /** Trip Code */
            trip_code: string;
        } & {
            [key: string]: unknown;
        };
        /** DriverSalaryTotals */
        DriverSalaryTotals: {
            /** Total Batta */
            total_batta: number;
            /** Total Payable */
            total_payable: number;
            /** Total Refund */
            total_refund: number;
        };
        /**
         * EscalationRow
         * @description A flagged/pending expense row in the WhatsApp escalation feed.
         */
        EscalationRow: {
            /**
             * Is Flagged
             * @default false
             */
            is_flagged: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ExpenseAccepted */
        ExpenseAccepted: {
            /** Accepted */
            accepted: boolean;
            /** Trip Code */
            trip_code: string;
            /** Exp Type */
            exp_type: string;
            /** Manager Status */
            manager_status: string;
            /** Is Flagged */
            is_flagged: boolean;
            /** Flag Reason */
            flag_reason?: string | null;
            /** Settlement Amount */
            settlement_amount?: number | null;
        };
        /** ExpenseActionResult */
        ExpenseActionResult: {
            /** Expense Id */
            expense_id: number;
            /** Status */
            status: string;
            /** Trip Code */
            trip_code: string;
            /** Label En */
            label_en?: string | null;
            /** Label Hi */
            label_hi?: string | null;
        };
        /**
         * FleetBilling
         * @description Billing-overview fleet block (extra keys allowed).
         */
        FleetBilling: {
            /**
             * Name
             * @default Your Fleet
             */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeStateResult
         * @description `PUT /benchmarks/home-state` — the caller's usual operating state.
         */
        HomeStateResult: {
            /** Home State Code */
            home_state_code?: string | null;
        };
        /**
         * LoginResult
         * @description `POST /auth/login` — no `data` wrapper (client reads token/user).
         */
        LoginResult: {
            /** Token */
            token: string;
            user: components["schemas"]["AuthUser"];
            /** Landing */
            landing: string;
        };
        /** LogoutResult */
        LogoutResult: {
            /** Logged Out */
            logged_out: boolean;
        };
        /** Plan */
        Plan: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Price */
            price?: number | null;
            /** Period */
            period?: string | null;
            /** Vehicle Limit */
            vehicle_limit?: number | null;
            /** Trial Days */
            trial_days?: number | null;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * ResourceAck
         * @description Generic `{ "id": N }` acknowledgement for created/updated rows.
         */
        ResourceAck: {
            /** Id */
            id: number;
        };
        /**
         * SessionRefreshResult
         * @description `POST /auth/refresh` — new sliding expiry (audit E-10).
         */
        SessionRefreshResult: {
            /** Expires At */
            expires_at: number;
        };
        /** SettleTripResult */
        SettleTripResult: {
            /** Trip Code */
            trip_code: string;
            /** Status */
            status: string;
        };
        /** ToggleAck */
        ToggleAck: {
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * TripDetailData
         * @description `GET /trips/{code}` payload: trip, its expenses, and the settlement.
         */
        TripDetailData: {
            /** Trip */
            trip: Record<string, never>;
            /** Expenses */
            expenses?: unknown[];
        } & {
            [key: string]: unknown;
        };
        /**
         * TripListItem
         * @description Trip listing item: a trip row plus its stats.
         */
        TripListItem: {
            stats?: components["schemas"]["TripStats"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TripStats
         * @description Aggregated stats for a trip (attached as `stats` on list rows).
         */
        TripStats: {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_DashboardOverview_"];
                };
            };
        };
    };
    api_dashboard_trends_api_v1_dashboard_trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_dict_"];
                };
            };
        };
    };
    api_auth_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
        };
    };
    api_auth_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMe"];
                };
            };
        };
    };
    api_auth_refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_SessionRefreshResult_"];
                };
            };
        };
    };
    api_auth_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_LogoutResult_"];
                };
            };
        };
    };
    api_change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ChangePasswordResult_"];
                };
            };
        };
    };
    api_trips_api_v1_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_TripListItem__"];
                };
            };
        };
    };
    api_create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_CreateTripResult_"];
                };
            };
        };
    };
    api_trip_detail_api_v1_trips__trip_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_TripDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settle_trip_api_v1_trips__trip_code__settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_SettleTripResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settled_trips_api_v1_settlements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_settlement_pdf_api_v1_settlements__trip_code__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_driver_salary_api_v1_driver_salary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_DriverSalary_"];
                };
            };
        };
    };
    api_whatsapp_escalations_api_v1_whatsapp_escalations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_EscalationRow__"];
                };
            };
        };
    };
    api_create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ExpenseAccepted_"];
                };
            };
        };
    };
    api_action_expense_api_v1_expenses__expense_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ExpenseActionResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_vehicles_api_v1_vehicles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_create_vehicle_api_v1_vehicles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
        };
    };
    api_update_vehicle_api_v1_vehicles__vid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_toggle_vehicle_api_v1_vehicles__vid__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ToggleAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_fleets_api_v1_fleets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_create_fleet_api_v1_fleets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
        };
    };
    api_get_plans_api_v1_fleets_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_update_fleet_api_v1_fleets__fid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_toggle_fleet_api_v1_fleets__fid__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ToggleAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
        };
    };
    api_update_user_api_v1_users__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_toggle_user_api_v1_users__uid__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ToggleAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_drivers_api_v1_drivers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    api_create_driver_api_v1_drivers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
        };
    };
    api_update_driver_api_v1_drivers__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_toggle_driver_api_v1_drivers__uid__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ToggleAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_benchmarks_api_v1_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_dict_str__Any__"];
                };
            };
        };
    };
    api_add_benchmark_favorite_api_v1_benchmarks__state_code__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BenchmarkFavoriteAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_remove_benchmark_favorite_api_v1_benchmarks__state_code__favorite_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BenchmarkFavoriteAck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_set_home_state_api_v1_benchmarks_home_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_HomeStateResult_"];
                };
            };
        };
    };
    api_sync_benchmarks_api_v1_benchmarks_sync_live_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_dict_str__Any__"];
                };
            };
        };
    };
    api_billing_overview_api_v1_billing_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BillingOverview_"];
                };
            };
        };
    };
    api_billing_subscribe_api_v1_billing_subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BillingSubscribeResult_"];
                };
            };
        };
    };
    api_billing_vehicle_slot_api_v1_billing_vehicle_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BillingVehicleSlotResult_"];
                };
            };
        };
    };
    api_billing_renew_api_v1_billing_renew__plan_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_BillingSubscribeResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_fleets_subscriptions_api_v1_fleets_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict__"];
                };
            };
        };
    };
    api_onboard_fleet_api_v1_fleets_onboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_dict_str__Any__"];
                };
            };
        };
    };
    api_list_trip_templates_api_v1_trip_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict__"];
                };
            };
        };
    };
    api_create_trip_template_api_v1_trip_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_ResourceAck_"];
                };
            };
        };
    };
    api_delete_trip_template_api_v1_trip_templates__tid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_notifications_api_v1_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_analytics_overview_api_v1_analytics_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    whatsapp_webhook_verify_api_v1_whatsapp_webhook_get: {
        parameters: {
            query?: {
                hub_mode?: string | null;
                hub_challenge?: string | null;
                hub_verify_token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_webhook_api_v1_whatsapp_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    whatsapp_send_api_v1_whatsapp_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never> | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_list_states_api_v1_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Data_list_dict_str__Any___"];
                };
            };
        };
    };
    billing_webhook_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
